# Dependabot will run on day 2 of each month at 02:19 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "19 2 2 * *"
    open-pull-requests-limit: 20
    assignees:
      - "BenAhrdt"
    versioning-strategy: "increase"
